
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: ollama
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: siegers/flask-ollama-chat:1.25
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: OLLAMA_HOST
          value: "http://ollama-service:11434"
        - name: OLLAMA_MODEL
          value: "qwen3:0.6b"
