
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: ollama
  labels:
    app: flask-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: flask-app
  type: NodePort
